fail_fast: false

default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^.circleci/recipe  # conda build recipes are templated
      - id: check-added-large-files
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: python
    hooks:
      - id: clang-format
        args: [--style=file, -i]
      - id: clang-tidy
        args: [--fix, --fix-errors]
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
