version: 2

jobs:

  build_test:
    docker:
      - image: ecoleai/ci
    environment:
      CONAN_USER_HOME: &conan_cache_dir /cache/conan
    steps:
      - checkout
      - restore_cache:
          keys:
            - &conan_cache_key >-
              conan-v1.1-{{
              arch }}-{{
              checksum "libecole/conanfile.txt" }}-{{
              checksum "libecole/tests/conanfile.txt" }}
            - conan-v1.1-{{ arch }}-
      - run:
          name: "CMake configure"
          command: >
            cmake -B build -D CMAKE_BUILD_TYPE=Release
      - save_cache:
          key: *conan_cache_key
          paths:
            - *conan_cache_dir
      - run:
          name: "CMake build"
          command: cmake --build build
      - run:
          name: "Test libecole"
          command: ./build/libecole/tests/test-libecole
      - run:
          name: "Install Python ecole"
          command: python3 -m pip install -I build/python
      - run:
          name: "Test Python ecole"
          command: python3 -m pytest python/tests

  check_format:
    docker:
      - image: ecoleai/ci
    steps:
      - checkout
      - run:
          name: "Check C++ formatting"
          command: |
            for file in $(find libecole python -name '*.cpp' -o -name '*.hpp'); do
              [ $? -eq 0 ] && clang-format --style=file $file | diff - $file
            done
      - run:
          name: "Check Python formatting"
          command: python3 -m black --check python/

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_test
      - check_format
